### ISSUE TITLE
可以打包成FIREFOX的插件吗？

### ISSUE THREAD

**Issue by ksgujie** [ttglad/learning#1]
可以打包成FIREFOX的插件吗？ 谢谢

**Comment by ttglad** [comment]
https://github.com/ttglad/learning/blob/master/addon-1.0.0-fx.xpi
试试这个吧

**Comment by ttglad** [comment]
> 可以打包成FIREFOX的插件吗？ 谢谢

https://addons.mozilla.org/zh-CN/firefox/addon/%E5%AD%A6%E4%B9%A0/
