### ISSUE TITLE
答题出现滑块验证时会一直循环不继续

### ISSUE THREAD

**Issue by janbobo** [ttglad/learning#10]
答题出现滑块验证时会一直循环不继续，滑块类名 nc-mask-display
能不能优化一下检测到滑块就跳过该答题从新开始

**Comment by ttglad** [comment]
这里没遇到这个问题，你那边有截图么

**Comment by janbobo** [comment]
现在没有截图 我下次在遇到就截图出来，不是每次都有这个滑块验证，昨天出来浏览器检查就看到类名是 nc-mask-display

**Comment by ttglad** [comment]
如果出现了，不答题，等到时候退出后，会重新答题的，应该不影响的。
