### ISSUE TITLE
firefox插件登陆后页面不断跳转

### ISSUE THREAD

**Issue by wenlong-li** [ttglad/learning#101]
老师您好，我反馈一个问题：3月27日登陆后，火狐学习插件登陆后页面不断跳转无法学习。

**Comment by ttglad** [comment]
> 老师您好，我反馈一个问题：3月27日登陆后，火狐学习插件登陆后页面不断跳转无法学习。

下载chrome浏览器，用最新版本试试

**Comment by hwq1126** [comment]
我这里用的谷歌浏览器，登录后也是不断的跳转，求原因

**Comment by zuictm** [comment]
我的也是
