### ISSUE TITLE
能否开发edge版本的呢，大佬

### ISSUE THREAD

**Issue by muyujw** [ttglad/learning#103]
crx文件拖到edge扩展里面显示 包无效:"CRX_HEADER_INVALID"，看来是不能直接用。edge浏览器个人感觉比原生chrome好用很多，都是Chromium内核，大佬能否考虑弄个edge版本的呢

**Comment by ttglad** [comment]
下载master代码，edge扩展使用开发者模式，加载下载的 release 文件夹，我试了是可以的

**Comment by ttglad** [comment]
下载master代码，edge扩展使用开发者模式，加载下载的 release 文件夹，我试了是可以的

**Comment by muyujw** [comment]
> 下载master代码，edge扩展使用开发者模式，加载下载的` release 文件夹，我试了是可以的 ![WX20230331-111019@2x](https://user-images.githubusercontent.com/7711709/229013325-54dee0f9-f9d4-4ffc-99cf-245a4842a7a4.png)

谢谢大佬，我试试

**Comment by aerowang66** [comment]
> 下载master代码，edge扩展使用开发者模式，加载下载的` release 文件夹，我试了是可以的 ![WX20230331-111019@2x](https://user-images.githubusercontent.com/7711709/229013325-54dee0f9-f9d4-4ffc-99cf-245a4842a7a4.png)

我试过了，edge确实可以使用，通过加载文件夹的方式。chrome也是需要通过加载文件夹，直接拖动crx我这里chrome会提示安全问题，由于不是来自应用商店。我最大的问题是360浏览器，此前版本的学习应该是1.0.7，此次更新后360浏览器提示如下错误。

![微信图片_20230403091503](https://user-images.githubusercontent.com/128773883/229391224-5c0f6739-fadf-4504-be3f-16f2c282a164.png)

**Comment by aerowang66** [comment]
目前用edge和chrome可以使用。谢谢老大
