### ISSUE TITLE
自动阅读和观看视频能否额外增加随机时间？

### ISSUE THREAD

**Issue by hanxuyuan** [ttglad/learning#106]
默认是1分钟，增减也都是固定1分钟为间隔

我想的是，学习1分钟的时间过于标准了，个人**险恶的怀疑**后台**是否可能**会判断这个时间进行处理？（可能暂时没有，以防万一）
所以能否1分钟时间额外增加一个10秒以内的随机时间？

例如第一个学习是1min+4s，第二个学习是1min+1s，第三个学习是1min+8s……

感觉这样是否会更加安全一点？

另外，可否增加挑战答题的功能？自动答5题即可……

最后，非常感谢大大！帮了我们大忙！懂的都懂，好人一生平安！star已给

**Comment by ttglad** [comment]
自动阅读和观看视频目前是已经增加了随机数，挑战答题的功能网页端根本就打不开，这个没法搞的

**Comment by ggzxccf** [comment]
已经很厉害了，谢谢大佬分分享！
