### ISSUE TITLE
3.0.7还能继续用吗？

### ISSUE THREAD

**Issue by suixinfeier** [ttglad/learning#107]

**Comment by ttglad** [comment]
啥意思，使用有问题么

**Comment by lll-code** [comment]
手机上可以用吗？怎么操作？

**Comment by 597145326** [comment]
使用3.0.7后收到第一次警告信息，要求实名认证

**Comment by ttglad** [comment]
> 使用3.0.7后收到第一次警告信息，要求实名认证

没遇到这个问题，一直在用的

**Comment by 597145326** [comment]
需要实名认证的注点意吧，那是第一次警告，会被封号的

**Comment by Northxw** [comment]
@suixinfeier @ttglad @597145326 我也是，周末的时候在家里的电脑装了 3.07 最新版插件，然后连续刷了三天，刚刚收到违规积分第一次警告，已经完成了实名认证，现在不知道还能不能继续刷了......

**Comment by 164724571** [comment]
学习违规提醒警示通知：“经系统检测，您的账号存在不规范学习行为，。。。，请规范学习行为。” @ttglad 我很早之前就已经实名了，所以和实名否无关。另，感谢ttglad和 小组其他伙伴提供的插件。

**Comment by ttglad** [comment]
目前我一直在用，没出现违规警告，强国的判断机制一般是频繁切换登录设备，或者多个登录一起刷

**Comment by Northxw** [comment]
> 目前我一直在用，没出现违规警告，强国的判断机制一般是频繁切换登录设备，或者多个登录一起刷

应该是切换设备导致的，之前我一直用笔记本刷分，周末在家就说用家里的台式机试试，结果就被警告了。

**Comment by 164724571** [comment]
我之前也是周末用家里的机器学习，但是没有警告，就今天警告了。

**Comment by Northxw** [comment]
> 我之前也是周末用家里的机器学习，但是没有警告，就今天警告了。

嘶，那可能是插件被识别了吧，看来好多人都被警告了，我也是今天被警告
