### ISSUE TITLE
手机上可以用吗？怎么操作？

### ISSUE THREAD

**Issue by lll-code** [ttglad/learning#108]

**Comment by gengzhe1981** [comment]
手机上安装支持crx的浏览器就可以使用。例如：狐猴浏览器。把crx传到手机里（建议根目录，容易寻找）、安装狐猴浏览器app、浏览器下面四叶草样图标——常用工具里的扩展管理——打开开发者模式——加载已解压的扩展程序——定位到手机里的crx。

**Comment by lll-code** [comment]
收到！
