### ISSUE TITLE
涉嫌刷分

### ISSUE THREAD

**Issue by andis220617** [ttglad/learning#115]
4.14已经被封号了

**Comment by Qindie957** [comment]
第一次警告后就没敢用了

**Comment by Qindie957** [comment]
封号多久，还能解封吗

**Comment by muyujw** [comment]
搞得我紧张的，只用来读文章和看视频会不会被警告啊，答题都简单，主要是文章和视频太耗时间了

**Comment by blublus** [comment]
网页插件也会警告吗，我看手机脚本被警告了好多

**Comment by TzeentchChosen** [comment]
同被封，封禁时长未知，目前能够正常累计积分，大家交流下情况吧！

**Comment by asdkkwekk** [comment]
已经被警告了，有一点点不敢用了怕被封禁

**Comment by a1468151338** [comment]
> 

还能登录吗，我的账号被强制注销了不能登录了

**Comment by lauren2018** [comment]
收到两次提醒了，之前就没事，这次怎么就能检测到。很好奇他们别后的机制。

**Comment by lauren2018** [comment]
最近也受到了

**Comment by ttglad** [comment]
建议你们不要换设备和ip刷题

**Comment by Qindie957** [comment]
还能被警告两次吗，不是第二次就封号，第三次封禁吗发自我的荣耀手机-------- 原始邮件 --------发件人： lauren2018 ***@***.***>日期： 2023年4月17日周一 半夜11:49收件人： ttglad/learning ***@***.***>抄送： Qindie957 ***@***.***>, Comment ***@***.***>主    题： Re: [ttglad/learning] 涉嫌刷分 (Issue #115)
收到两次提醒了，之前就没事，这次怎么就能检测到。很好奇他们别后的机制。

**Comment by andis220617** [comment]
> 还能被警告两次吗，不是第二次就封号，第三次封禁吗发自我的荣耀手机-------- 原始邮件 --------发件人： lauren2018 ***@***.***>日期： 2023年4月17日周一 半夜11:49收件人： ttglad/learning ***@***.***>抄送： Qindie957 ***@***.***>, Comment ***@***.***>主 题： Re: [ttglad/learning] 涉嫌刷分 (Issue #115) 收到两次提醒了，之前就没事，这次怎么就能检测到。很好奇他们别后的机制。 —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

警告三次了，下次再检测到就是封禁了。

**Comment by Qindie957** [comment]
> 建议你们不要换设备和ip刷题

大佬，有没有可能通过设置不一样的学习时间来规避检测，目前收到警告过一次，关闭自动答题，暂时未被二次警告
![image](https://user-images.githubusercontent.com/64944249/233767488-968c2ee3-f287-452e-9daa-e09488e1cc90.png)

**Comment by ttglad** [comment]
> > 建议你们不要换设备和ip刷题
> 
> 大佬，有没有可能通过设置不一样的学习时间来规避检测，目前收到警告过一次，关闭自动答题，暂时未被二次警告 ![image](https://user-images.githubusercontent.com/64944249/233767488-968c2ee3-f287-452e-9daa-e09488e1cc90.png)

选择的时间，寿面会加上随机数的

**Comment by realbbits** [comment]
> 同被封，封禁时长未知，目前能够正常累计积分，大家交流下情况吧！

我的也是这样。这样的是首次警告？

**Comment by hutaohutc** [comment]
> 设置不一样的学习时间来规避检测，目前收到警告过一次，关闭自动答题，暂时未被二次警告

只要关闭自动答题就可以？？
