### ISSUE TITLE
被警告了，疑似学习的内容时效有问题

### ISSUE THREAD

**Issue by hanxuyuan** [ttglad/learning#118]
我想说，有没有可能，是根据大数据每个人看视频或者看文章的时长来判断？
作者大大提过加了随机时长，貌似是10s以内的随机数，导致用户数据习惯过于规律了？比如1min2s，1min5s这种

要不就不设定固定时间+随机时间，而是直接1min~3min之间的彻底随机时间，让变异系数看起来比较大？比如1min10s、2min48s、2min2s这种。

————————————————————————————————————————
另外我发现一个问题，自主学习观看的文章或者视频基本都是半年前的……都不是最新的
我今天短暂的测试了一下，一个视频是去年11月份，一个文章是去年8月份。

从这个角度来说，行为的确不太正常
————————————————————————————————————————
另外答题那个，似乎网页版的容易触发滑动验证？

**Comment by Kkkkkun** [comment]
淦，我直接被封禁了

**Comment by lxz12** [comment]
哈哈,同被封禁7天,警告都没有

**Comment by hanxuyuan** [comment]
另外我发现一个问题，自主学习观看的文章或者视频都是半年前的……都不是最新的，这个的确不太正常

**Comment by realbbits** [comment]
> 哈哈,同被封禁7天,警告都没有

怎么看封禁几天？

**Comment by JFF11** [comment]
喜提警告一次！

**Comment by realbbits** [comment]
> 喜提警告一次！

我的前几天有条封禁消息，没到期时间，期间无法积分。这几天都正常积分的……

**Comment by hanxuyuan** [comment]
> > 喜提警告一次！
> 
> 我的前几天有条封禁消息，没到期时间，期间无法积分。这几天都正常积分的……

你应该是第二次被警告了，第一次警告只让实名认证，第二次封禁期间没有积分，第三次积分清零，第四次直接销号

**Comment by hanxuyuan** [comment]
> 哈哈,同被封禁7天,警告都没有

应该是你没注意消息，貌似是第二次警告同时封禁

**Comment by realbbits** [comment]
> > > 喜提警告一次！
> > 
> > 
> > 我的前几天有条封禁消息，没到期时间，期间无法积分。这几天都正常积分的……
> 
> 你应该是第二次被警告了，第一次警告只让实名认证，第二次封禁期间没有积分，第三次积分清零，第四次直接销号

我的应该是首次。消息标题是 处罚警告，内容又是封禁，期间无法积分。收到消息后的这几天积分和点点通都是正常的
