### ISSUE TITLE
希望能加入自主选择《每日答题、、每周答题、专项答题》功能

### ISSUE THREAD

**Issue by wywebcn** [ttglad/learning#12]
有时只需要文章与视频学习、不需要自动答题。此前已经有学习小熊实现自行选择是否需要自动答题的功能。希望开发者能加入自由选择《每日答题》、《每周答题》、《专项答题》功能。

**Comment by ttglad** [comment]
安排

**Comment by wywebcn** [comment]
加油，看好你哟

**Comment by ttglad** [comment]
> 

下载最新版，尝试下吧

**Comment by wywebcn** [comment]
感谢作者，已经下载，正在测试当中……

**Comment by wywebcn** [comment]
窗口中并未出现有选项可以勾选，待明天再试试。
