### ISSUE TITLE
插件登录后， 过一段时间，积分页面和做任务页面空白是什么原因？

### ISSUE THREAD

**Issue by Wxin96** [ttglad/learning#13]
使用的是Chrome 版本 97.0.4692.71浏览器， 是在chrome哪里配置吗？

**Comment by ttglad** [comment]
本人用的也是谷歌，没遇到过这个情况啊

**Comment by Wxin96** [comment]
> 本人用的也是谷歌，没遇到过这个情况啊

我查了一下应该chrome的问题，详见https://www.zhihu.com/question/348037683，长时间不活动页面被discard了。准备测试一下试试
