### ISSUE TITLE
感谢开发作者用心更新，已经下载正在测试中……

### ISSUE THREAD

**Issue by wywebcn** [ttglad/learning#14]
之前的留言无故消失了，感谢开发作者用心更新，已经下载正在测试中……
但是目前发现学习的窗口中并没有可自行出现可供勾选是否每周答题、、专项答题、每日答题等选项。扩展选项也是灰色
，所以一直未能找着。未能了解开发者设置勾选的逻辑，还得慢慢地熟悉摸索。今天学习已经完成，明天我再试试会不会有选项。
PS：也许有人会说为什么要这么麻烦的选项，相信很多人都知道每周三是学习统计排名的时间，如果周一就把每周答题给自动学了，会严重影响学习积分统计排名的。
这个功能非常必要，这个功能非常必要，这个功能非常必要，重要事情说三遍！
开发作者用过学习小熊，应该也知道学习小熊在扩展选项卡和学习弹窗内都有明显的选项可供勾选，建议开发作者在扩展选项中加入此类功能，直观明了。
顺祝开发作者工作顺心，万事如意。
期盼下一个版本……

**Comment by ttglad** [comment]
下载最新版本的文件后，chrome要刷新或者删除后重新安装，火狐浏览器安装最新版本2.0.1
具体使用方法，点击扩展，会出现  `开始学习` 按钮，下面是默认三个答题选项，选中表示自动答题。

**Comment by wywebcn** [comment]
赞，这么迅速，马上测试。谢谢

**Comment by wywebcn** [comment]
测试效果很好，但发现个答题小BUG——专项答题居然错了一题。
《“纪念红军长征胜利85周年”专项答题》自动答题为C，正确答案应该是A。
下列红军长征发生的事件，按先后顺序排列正确的是（）。
①强渡大渡河
②四渡赤水
③巧渡金沙江
④飞夺泸定桥
⑤翻越夹金山
来源：《中国共产党简史》 （人民出版社、中共党史出版社2021年版）
A. ②③①④⑤
B. ③②④①⑤
C. ④③②①⑤
答案解析
正确答案：A
红军长征发生的历史事件，按顺序排列是：四渡赤水、巧渡金沙江、强渡大渡河、飞夺泸定桥、翻越夹金山。

**Comment by ttglad** [comment]
关于自动答题部分，`每周答题` 和 `专项答题` 有视频题或者一些答题提示不明确的 会答题失败，对于要求成功率100%的，建议手动答题。
`每日答题` 可以做很多组，所以打错会自动回答第二组，直到满分位置，不受影响。
