### ISSUE TITLE
提示出现“渠道接口变更，请等待新版本发布”

### ISSUE THREAD

**Issue by wywebcn** [ttglad/learning#16]
提示出现“渠道接口变更，请等待新版本发布”

**Comment by ttglad** [comment]
这个应该是网速过慢，导致的，下个版本修复下

**Comment by ttglad** [comment]
> 提示出现“渠道接口变更，请等待新版本发布”

已修复，下载新版本试试

**Comment by wywebcn** [comment]
已经用上了，暂时出现过一次，目前使用正常

**Comment by ttglad** [comment]
> 已经用上了，暂时出现过一次，目前使用正常

你那网速估计不好，出现一次，会继续执行的，不会退出
