### ISSUE TITLE
大佬 使用会否有封号 潜在风险

### ISSUE THREAD

**Issue by xuexizhedejia** [ttglad/learning#19]
功能很好用，非常节省学习的时间。但是在网上查询到一些封号新闻，请问这个会可能被检测到吗？感觉答题速度过快，会被检测

**Comment by ttglad** [comment]
> 功能很好用，非常节省学习的时间。但是在网上查询到一些封号新闻，请问这个会可能被检测到吗？感觉答题速度过快，会被检测

答题已经有随机耗时等待的机制了，比手动的要慢一点
