### ISSUE TITLE
浏览器没法添加

### ISSUE THREAD

**Issue by hanliren** [ttglad/learning#2]
本人试验了edge 、谷歌、火狐等浏览器，没法安装这个插件

**Comment by ttglad** [comment]
> 本人试验了edge 、谷歌、火狐等浏览器，没法安装这个插件

谷歌浏览器要下载源码，安装，参考安装文档，
火狐直接搜索  `学习强国助手` 安装插件

**Comment by ywe1ess** [comment]
谷歌完美使用

**Comment by ttglad** [comment]
> 谷歌完美使用

好用的话，给个星

**Comment by liuqianli1** [comment]
该扩展程序未列在 Chrome 网上应用店中，并可能是在您不知情的情况下添加的。

**Comment by ttglad** [comment]
> 该扩展程序未列在 Chrome 网上应用店中，并可能是在您不知情的情况下添加的。

在地址栏输入 chrome://extensions 并回车，勾选 开发者模式 -> 加载已解压的扩展程序, 选择从 Source code 解压的 release 文件夹。
