### ISSUE TITLE
每日答题答错有干扰，建议如下修改

### ISSUE THREAD

**Issue by McMug2020** [ttglad/learning#20]
if (document.querySelector(".exam-weekly-detail") != null || document.querySelector(".exam-paper-detail") != null) {                        chrome.runtime.sendMessage({"method": "answerError"});
                    }

**Comment by ttglad** [comment]
> if (document.querySelector(".exam-weekly-detail") != null || document.querySelector(".exam-paper-detail") != null) { chrome.runtime.sendMessage({"method": "answerError"});
> }

这个只是一个提示，人工不介入也会进行下去的。
