### ISSUE TITLE
视频学习频道失效问题反馈

### ISSUE THREAD

**Issue by McMug2020** [ttglad/learning#21]
视频学习频道“永远的丰碑”失效了，一直在学澎湃，可以替换为如下频道：
        "eta8vnluqmd",   // 军事科技
        "16421k8267l",   // 强军V视
        "41gt3rsjd6l8",   // 绿色发展

**Comment by ttglad** [comment]
> 视频学习频道“永远的丰碑”失效了，一直在学澎湃，可以替换为如下频道： "eta8vnluqmd", // 军事科技 "16421k8267l", // 强军V视 "41gt3rsjd6l8", // 绿色发展

下个版本放上去

**Comment by ttglad** [comment]
> 视频学习频道“永远的丰碑”失效了，一直在学澎湃，可以替换为如下频道： "eta8vnluqmd", // 军事科技 "16421k8267l", // 强军V视 "41gt3rsjd6l8", // 绿色发展

v2.0.4版本已添加

**Comment by McMug2020** [comment]
收到，感谢😊
