### ISSUE TITLE
每日答题、专项答题、每周答题检索顺序需要调整

### ISSUE THREAD

**Issue by 20058668** [ttglad/learning#22]
每日答题、专项答题、每周答题检索顺序需要调整，目前的顺序好像是以前年份开始检索，如果有以前年度部分就做以前年度，这样的话就会出现   当日积分45但是年度积分小于45。
最好的设计 是 今年有 没做的，先做今年的，今年做完了就找以前年度的内容做，直到做完。

**Comment by ttglad** [comment]
> 每日答题、专项答题、每周答题检索顺序需要调整，目前的顺序好像是以前年份开始检索，如果有以前年度部分就做以前年度，这样的话就会出现 当日积分45但是年度积分小于45。 最好的设计 是 今年有 没做的，先做今年的，今年做完了就找以前年度的内容做，直到做完。

安排

**Comment by ttglad** [comment]
> 每日答题、专项答题、每周答题检索顺序需要调整，目前的顺序好像是以前年份开始检索，如果有以前年度部分就做以前年度，这样的话就会出现 当日积分45但是年度积分小于45。 最好的设计 是 今年有 没做的，先做今年的，今年做完了就找以前年度的内容做，直到做完。

下载2.0.4版本，我使用了一次，没问题。

**Comment by 20058668** [comment]
辛苦了

**Comment by wywebcn** [comment]
这个可有可无，答题顺序以以前年份开始检索没毛病。比如说有人学习组需要屯题冲头名，如果多人都在一个月答题的，那样子在多人抢头名的情况一下子把今年的全答了，而且头名无法保证，就会浪费答题分。所以有人会隐忍屯几个月题避其他人锋芒，在某一月出击拿头名。

**Comment by wywebcn** [comment]
还是希望开会者能考虑兼顾加个检索答题时间选项，哈哈哈， 正所谓众口难调，难为开发作者了。

**Comment by ttglad** [comment]
这个主要是我没你们的具体使用需求，我自己来说，只要积分够高就可以了。

**Comment by 20058668** [comment]
我们这里有年度积分要求，就是说每年要多少分。
比如说有人学习组需要屯题冲头名,我觉得这种出风头的事情，最好自己动手手工做。哈哈，我们是来混日子的。

**Comment by wywebcn** [comment]
哈哈哈，不存在出风头。这是地方考核机制的问题。

**Comment by 20058668** [comment]
偷偷地悠着点用才是硬道理，冒头容易被抓，枪打出头鸟。
