### ISSUE TITLE
如何修改脚本执行的顺序？

### ISSUE THREAD

**Issue by IsYexin** [ttglad/learning#24]
您好，我想运行程序后先进行答题模块，然后再是阅读文章和视频，请问大佬在哪个文件里可以自行修改？

**Comment by ttglad** [comment]
> 您好，我想运行程序后先进行答题模块，然后再是阅读文章和视频，请问大佬在哪个文件里可以自行修改？

v2.0.5版本增加了配置页面，可以试试

**Comment by wywebcn** [comment]
> > 您好，我想运行程序后先进行答题模块，然后再是阅读文章和视频，请问大佬在哪个文件里可以自行修改？
> 
> v2.0.5版本增加了配置页面，可以试试

配置功能很棒，实现了解决之前的各种纠结问题。

**Comment by ttglad** [comment]
> 

感谢大家集思广益
