### ISSUE TITLE
点击插件时，窗口没有对准登陆二维码，每次都要手动拉窗口

### ISSUE THREAD

**Issue by anby1** [ttglad/learning#26]
屏幕是竖屏，分辨率1080*1920

**Comment by gspsp** [comment]
这又不影响你懒人强国。

**Comment by ttglad** [comment]
> 屏幕是竖屏，分辨率1080*1920

打开不要动，等几秒会自动滚动到二维码位置

**Comment by 79133576** [comment]
> 

![微信截图_20220308120137](https://user-images.githubusercontent.com/66161710/157163839-a2f1725b-3f1f-42e6-b618-ccaa75c9d45b.png)
横屏显示器会定位成功，但如果是竖屏就会定位到图上的位置

**Comment by 79133576** [comment]
> > 屏幕是竖屏，分辨率1080*1920
> 
> 打开不要动，等几秒会自动滚动到二维码位置


![微信截图_20220308120137](https://user-images.githubusercontent.com/66161710/157164108-fc1c7866-fc6a-4df4-a14a-3f35454191f6.jpg)
横屏显示器会定位成功，但如果是竖屏就会定位到图上的位置，导致无法直接扫二维码

**Comment by ghjzt** [comment]
你改一下login.js文件，我的原来也不行，改了一下就可以了。
chrome.runtime.sendMessage({"method": "chooseLogin"}, {}, function (response) {
    window.onload = function () {

        setTimeout(function () {
            document.querySelector(".qrcode-box").scrollIntoView({
                behavior: "smooth",
				block:"center",
				inline:"center"
            });
        }, 500);

        chrome.runtime.sendMessage({"method": "checkLogin"});
    }
});
