### ISSUE TITLE
能不能实现每天定时自动执行

### ISSUE THREAD

**Issue by 256kb** [ttglad/learning#29]
能不能实现每天定时自动执行？每天早上10点自动运行。
想想都美

**Comment by wywebcn** [comment]
+1
以前就有这想法，但考虑这个功能应该有点棘手，所以没敢开口麻烦开发者。

**Comment by left0ver** [comment]
呃，这个感觉有点难，这个插件还是得依赖于浏览器的，除非你一直开着电脑或许可以

**Comment by ttglad** [comment]
这个是可以考虑用后台脚本实现，但是有封号的危险，还是老老实实浏览器操作下吧

**Comment by RuFeng08** [comment]
电脑版可以每天不用扫码登录吗
