### ISSUE TITLE
请问运行后窗口关闭了会有什么后果？

### ISSUE THREAD

**Issue by Norach-I** [ttglad/learning#3]
你好，昨天第一次运行，请问运行开始后，调整了下弹窗大小，之后新闻视频播放完了窗口就定住了，我把弹窗全部关闭后，再重新运行，发现会只停留在我的积分界面。。。还有一个问题是，再后面只剩答题部分了，弹窗也是只定在我的积分界面，我等了估计3~4分钟，依旧还在我的积分界面。正常情况下，答题部分运行也是停留在我的积分界面嘛？

**Comment by ttglad** [comment]
会弹出两个界面，一个是积分界面，不用关心，另外一个是运行界面，运行界面会根据情况来打开文、视频、答题！

**Comment by Norach-I** [comment]
请问如果点击运行后，只有积分界面，该怎么处理？

**Comment by ttglad** [comment]
> 请问如果点击运行后，只有积分界面，该怎么处理？

没遇到过这个情况，建议重新关闭浏览器，再试一次
