### ISSUE TITLE
需要大佬更新

### ISSUE THREAD

**Issue by WameING** [ttglad/learning#32]
目前又不能答题了

**Comment by ttglad** [comment]
我一直在用，都是可以的啊，有可能网速不好？

**Comment by rabbit-712** [comment]
到每日答题的界面就不动了，一直就在第一题界面

**Comment by left0ver** [comment]
啊？我的也可以，我的没什么问题，你可以把插件卸载了，重新安装一下试试

**Comment by WameING** [comment]
好了解决了，我原本用的是火狐浏览器，插件卸载了重新安装并没有得到解决，我在谷歌浏览器安装了插件，已经正常运行了~这个插件真牛逼，太省事了！！

**Comment by tigerandlio** [comment]
这个插件真牛逼，太省事了！但是需要更新下题库了。

**Comment by gspsp** [comment]
> 这个插件真牛逼，太省事了！但是需要更新下题库了。

什么题库，这个插件没有题库。

**Comment by tigerandlio** [comment]
有些题的答案不对，我以为是有题库的。

summer ***@***.***>于2022年4月2日 周六上午10:51写道：

**Comment by ttglad** [comment]
没有题库的，目前有部分答题定位不到准确答案，慎用，建议优先 每周答题、专项答题  报错浏览器会提示，可以手动答题

**Comment by alexletsgo** [comment]
> 

请问大佬怎么加载到别的浏览器里？我下不到CRX文件

**Comment by gspsp** [comment]
> > 
> 
> 请问大佬怎么加载到别的浏览器里？我下不到CRX文件

直接在code中点release.crx就能下载。
