### ISSUE TITLE
在播放视频时，可否同时在手机端答题。

### ISSUE THREAD

**Issue by tigerandlio** [ttglad/learning#39]

**Comment by anby1** [comment]
浏览器插件播放视频时，在手机端答题，有人这么做被警告了，具体参考
![image](https://user-images.githubusercontent.com/66161710/167173901-1e35ab32-8d6f-4667-a3d1-1f73e0948ced.png)
![image](https://user-images.githubusercontent.com/66161710/167173929-7be86c18-359c-4fc7-8def-f6927367488e.png)

**Comment by ttglad** [comment]
我目前一直是这么使用的，没有被警告过，到公司打开插件，然后手机上面也答题。
