### ISSUE TITLE
如何在chrome中多开

### ISSUE THREAD

**Issue by alanzed555** [ttglad/learning#4]
在Chrome中创建多个用户，使用不同的用户运行。？？？

如何在chrome中创建多个用户呢？3q。

**Comment by ttglad** [comment]
> 在Chrome中创建多个用户，使用不同的用户运行。？？？
> 
> 如何在chrome中创建多个用户呢？3q。

在Chrome中创建多个浏览器用户，切换用户试试

**Comment by alanzed555** [comment]
> 
每开一个新的标签页就是一个浏览器用户吗？

**Comment by ttglad** [comment]
> > 
> 
> 每开一个新的标签页就是一个浏览器用户吗？

不是的，是谷歌浏览器的用户，添加多个用户，每个用户都是独立的一套
