### ISSUE TITLE
最新版变成全屏

### ISSUE THREAD

**Issue by bestwangyu** [ttglad/learning#43]
首先仰望下大神
更新3.0后，变成全屏网页了

**Comment by ttglad** [comment]
是滴呢，目前是统一设置成全屏了

**Comment by wywebcn** [comment]
全屏后不是很方便，学习中每次自动切换新页面时会窗口自动最前面，体验效果影响有点大。望能加个功能处行设置窗口大小与是否窗口自动最前面

**Comment by wywebcn** [comment]
> 全屏后不是很方便，学习中每次自动切换新页面时会窗口自动最前面，体验效果影响有点大。望能加个功能处行设置窗口大小与是否窗口自动最前面。
