### ISSUE TITLE
新版本可以像旧版本206那样，点进去就静音吗？

### ISSUE THREAD

**Issue by yuepalm** [ttglad/learning#46]
新版本可以像旧版本206那样，点进去就静音吗？

**Comment by wywebcn** [comment]
这个可以在标签页上自行设置当前网站在标签页静音即可。

**Comment by yuepalm** [comment]
> 这个可以在标签页上自己设置当前网站在标签页静音。

我用的是360极速浏览器，点开后是单独窗口，没有标签页（很难描述），无法单独设置标签页静音的。

**Comment by yuepalm** [comment]
感觉开发者是有做静音处理的，就是视频播了一会后，才会静音。

**Comment by ttglad** [comment]
目前是做了静音的，除非是学习的文章里面视频自动播放的，那是没法处理的

**Comment by ttglad** [comment]
v3.0.2已修复

**Comment by yuepalm** [comment]
> v3.0.2 已修复

感谢
