### ISSUE TITLE
弄完文章之后不能答题

### ISSUE THREAD

**Issue by Wee133** [ttglad/learning#49]
每一次文章读完之后，每周答题那些弄不了

**Comment by ttglad** [comment]
> 每一次文章读完之后，每周答题那些弄不了

换chrome浏览器，一直使用比较稳定

**Comment by Wee133** [comment]
但是我不明白chrome浏览器如何弄




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ttglad/learning"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月20日(星期五) 上午9:02
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ttglad/learning] 弄完文章之后不能答题 (Issue #49)





  
每一次文章读完之后，每周答题那些弄不了
  
换chrome浏览器，一直使用比较稳定

**Comment by ttglad** [comment]
这个只能开发者模式了，因为注册谷歌开发者比较麻烦，还得要国际信用卡付款。

这个有个我开发的时候写的[文章](https://www.jianshu.com/p/5464872fef93)，你可以参考下，
下载这个插件的release版本，然后按照下面的文章配置开发者
![image](https://user-images.githubusercontent.com/7711709/169466922-a5446d40-d42c-4fc8-a6f7-b089694d80aa.png)

**Comment by Wee133** [comment]
感谢大佬，爱啦爱啦
