### ISSUE TITLE
360极速浏览器无法使用

### ISSUE THREAD

**Issue by SZnAl** [ttglad/learning#55]
<img width="775" alt="微信截图_20220530093120" src="https://user-images.githubusercontent.com/19545460/170901604-13b2536d-7d6a-4a52-adb4-bc1215cbc4e4.png">
<img width="42" alt="微信截图_20220530093111" src="https://user-images.githubusercontent.com/19545460/170901608-942a2775-59a7-4352-8c61-61842f905ebf.png">
加载插件后，点击提示 “无法加载或更改网站的数据”，chrome可以正常使用，请问是怎么回事呢？

**Comment by ttglad** [comment]
我这边试了360极速是可以滴，你可以看看是不是权限设置的问题

**Comment by SZnAl** [comment]
感谢回复~
<img width="796" alt="微信截图_20220531090116" src="https://user-images.githubusercontent.com/19545460/171073187-f2786bf5-5056-43c5-877a-0f38980d26ca.png">
权限设置里没有问题呀
之前一直在360极速都是可以用的，上次有更新 拖入新的包后就显示来自不安全的...然后按钮就是置灰的状态

**Comment by 20058668** [comment]
版本3.0.4在360极速中不能使用，按钮变成灰色了

**Comment by ttglad** [comment]
> 在版本2.0.6是可以用的，3.0版本就不能用了，一直灰色

如果是360浏览器，可以使用2.0.6。3.0以上版本是升级到了mv3，谷歌是强制要升级，不然后期不可使用了

**Comment by 20058668** [comment]
> > 在版本2.0.6是可以用的，3.0版本就不能用了，一直灰色
> 
> 如果是360浏览器，可以使用2.0.6。3.0以上版本是升级到了mv3，谷歌是强制要升级，不然后期不可使用了

测试发现版本3.0.4     在360极速浏览器X  64位 可以用 ，360极速浏览器32位不可以用
