### ISSUE TITLE
文章能不能刷新到2022 的文章呢，谢谢

### ISSUE THREAD

**Issue by xiaofangg** [ttglad/learning#57]
文章能不能刷新到2022 的文章呢，谢谢

**Comment by ttglad** [comment]
> 文章能不能刷新到2022 的文章呢，谢谢

为啥需要刷到2022年的文章，这个是哪里有要求么

**Comment by xiaofangg** [comment]
> > 文章能不能刷新到2022 的文章呢，谢谢
> 
> 为啥需要刷到2022年的文章，这个是哪里有要求么

上级要求，刷最新的，下级只能照做，谢谢大佬
