### ISSUE TITLE
学习时长建议

### ISSUE THREAD

**Issue by lssmoon2019** [ttglad/learning#58]
建议每篇文章或视频的阅读时间设置为1~2分钟之间随机，而不是刚好整数时间。不然很明显。

**Comment by ttglad** [comment]
随机数已经加了，设置的是最短学习时间。

**Comment by lssmoon2019** [comment]
> 随机数已经加了，设置的是最短学习时间。

我看只有1，2，3分钟三个时间选择呢。是否实际是1分16秒、1分23秒这样的随机呢

**Comment by ttglad** [comment]
> 是否实际是1分16秒、1分23秒这

会在你选择的时间上 + 10秒以内的随机

**Comment by Asif0001** [comment]
> 随机数已经加了，设置的是最短学习时间。
大佬这个随机数加的很合理哈哈哈！
