### ISSUE TITLE
可以设置一下获取的分数麽 不要天天都45....

### ISSUE THREAD

**Issue by chaojiniuniu** [ttglad/learning#60]
如题

**Comment by ttglad** [comment]
不是有配置么，你可以配置某些项目不学习即可

**Comment by justyre** [comment]
> 

好像每周答题从6月起不更新了，现在就算选项全开，每天都只有40分……不知能提升回45分么？

**Comment by ttglad** [comment]
> > 
> 
> 好像每周答题从6月起不更新了，现在就算选项全开，每天都只有40分……不知能提升回45分么？

每周答题答完了就不会了，官方每周答题不会更新了 有公告的

**Comment by justyre** [comment]
> > > 
> > 
> > 
> > 好像每周答题从6月起不更新了，现在就算选项全开，每天都只有40分……不知能提升回45分么？
> 
> 每周答题答完了就不会了，官方每周答题不会更新了 有公告的

所以目前每天只能40分了，是吧？未来是否有可能加入挑战答题之类别的模块呢？谢谢
