### ISSUE TITLE
谷歌浏览器：为什么一直停留在1分，开启了自动答题也没效果，页面一直停留着还要我手动点击下一题

### ISSUE THREAD

**Issue by yoghurtxu** [ttglad/learning#61]
谷歌浏览器：为什么一直停留在1分，开启了自动答题也没效果，页面一直停留着还要我手动点击下一题
![image](https://user-images.githubusercontent.com/31319378/174740789-8808fbe0-ed92-4b3d-8834-a3dc199b1568.png)

**Comment by ttglad** [comment]
谷歌浏览器，我这边一直使用没问题，具体原因，我这边看不到你的场景，也解决不了。你试试阅读文章是否可以。

**Comment by yoghurtxu** [comment]
> 

你的chrome啥版本的呢

**Comment by ttglad** [comment]
> 

102.0.5005.115（正式版本） 谷歌商店搜索 `学习强国` ，安装下官方的扩展试试
