### ISSUE TITLE
大佬，有木有封号风险

### ISSUE THREAD

**Issue by JiangBenCoder** [ttglad/learning#63]

**Comment by ttglad** [comment]
完全没有

**Comment by BBFKER** [comment]
一些人用其他的工具刷分被禁啦，还是要小心点

**Comment by PeiPei11** [comment]
这个有被封号的案例吗

**Comment by ttglad** [comment]
> 

目前没有，这个是浏览器插件，一般不会违规的

**Comment by xiehuihui** [comment]
> 大佬，建议可以设置随机时间阅读和答题，每次都是固定的阅读时间和答题时间容易被算法识别出来答题不太科学

**Comment by xiehuihui** [comment]
> > 
> 
> 目前没有，这个是浏览器插件，一般不会违规的

大佬，建议可以设置随机时间阅读和答题，每次都是固定的阅读时间和答题时间容易被算法识别出来答题不太科学
