### ISSUE TITLE
请问我用最新的chrome浏览器为什么304还是不能用

### ISSUE THREAD

**Issue by iwbb2000** [ttglad/learning#64]
？

**Comment by ttglad** [comment]
这里我也看不着啥情况，可以截图发我邮箱我看下

**Comment by zhuohui** [comment]
Manifest version 2 is deprecated, and support will be removed in 2023. See https://developer.chrome.com/blog/mv2-transition/ for more details.

**Comment by xxrlzzz** [comment]
重装插件试试吧, 感觉chrome有点抽风
