### ISSUE TITLE
学习强国每周答题能不能不做了，每次一到每周答题那个界面，就一直卡在哪儿了

### ISSUE THREAD

**Issue by 15923146369** [ttglad/learning#68]

**Comment by left0ver** [comment]
<img width="247" alt="image" src="https://user-images.githubusercontent.com/89240290/189517014-c7762747-7ee9-464f-bbfb-fc907f68341f.png">
设置里面可以选择是否做每日答题，你设置一下即可

**Comment by 15923146369** [comment]
不行，我的右键点出来是这个




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ttglad/learning"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月11日(星期天) 下午3:33
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ttglad/learning] 学习强国每周答题能不能不做了，每次一到每周答题那个界面，就一直卡在哪儿了 (Issue #68)





 

 设置里面可以选择是否做每日答题，你设置一下即可

**Comment by left0ver** [comment]
> 不行，我的右键点出来是这个
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "ttglad/learning" ***@***.***&gt;; 发送时间:&nbsp;2022年9月11日(星期天) 下午3:33 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [ttglad/learning] 学习强国每周答题能不能不做了，每次一到每周答题那个界面，就一直卡在哪儿了 (Issue #68) 设置里面可以选择是否做每日答题，你设置一下即可 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;
，
我看不到哇，可能版本升级改掉了吧，你可以看以前的版本或者我仓库fork的，我可以设置是否做每周答题

**Comment by 15923146369** [comment]
好的，谢谢哈




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ttglad/learning"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月11日(星期天) 晚上6:11
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ttglad/learning] 学习强国每周答题能不能不做了，每次一到每周答题那个界面，就一直卡在哪儿了 (Issue #68)





  
不行，我的右键点出来是这个
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "ttglad/learning" @.&gt;; 发送时间:&nbsp;2022年9月11日(星期天) 下午3:33 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [ttglad/learning] 学习强国每周答题能不能不做了，每次一到每周答题那个界面，就一直卡在哪儿了 (Issue #68) 设置里面可以选择是否做每日答题，你设置一下即可 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&gt;
 ，
 我看不到哇，可能版本升级改掉了吧，你可以看以前的版本或者我仓库fork的，我可以设置是否做每周答题
