### ISSUE TITLE
网页版出现了滑块验证功能！

### ISSUE THREAD

**Issue by Banksy-2187** [ttglad/learning#75]
今天答题提交时候发现弹出了滑块验证，无法自动完成，需要配合手动验证之后答题结果才能提交。希望大佬适配

**Comment by gavincilp** [comment]
同问，大佬能不能把它搞定

**Comment by Estherbad** [comment]
同问，大大加油啊

**Comment by maomaoge001** [comment]
同问滑块验证是什么情况

**Comment by bartleyarchil** [comment]
出现这个滑块验证赶脚有点危险，“证明”有人盯上了？没必要这样吧

**Comment by McMug2020** [comment]
滑动验证代码如下，供参考

            function ncSlideVerify() {
                if (nc_mask != null && getComputedStyle(nc_mask).display !== 'none') {
                    var btn_slide = document.querySelector(".btn_slide");
                    var mousedown = document.createEvent("MouseEvents");
                    if (btn_slide != null) {
                        var btn_slide_rect = btn_slide.getBoundingClientRect();
                        var x = btn_slide_rect.left + btn_slide_rect.width * (parseInt(Math.random() * 5) / 10 + 0.2);
                        var y = btn_slide_rect.top + btn_slide_rect.height / 2;
                    }
                    var nc_scale = document.querySelector(".nc_scale");
                    if (nc_scale != null) { var w = nc_scale.getBoundingClientRect().width; }
                    
                    //点击滑块
                    mousedown.initMouseEvent("mousedown", true, true, window, 0, x, y, x, y, false, false, false, false, 0, null);
                    if (btn_slide != null) { btn_slide.dispatchEvent(mousedown); }
                    
                    var dx = 0;
                    var dy = 0;
                    //滑动滑块
                    intervaltimer = setInterval(function() {
                        var mousemove = document.createEvent("MouseEvents");
                        var _x = x + dx;
                        var _y = y + dy;
                        mousemove.initMouseEvent("mousemove", true, true, window, 0, _x, _y, _x, _y, false, false, false, false, 0, null);
                        if (btn_slide != null) { btn_slide.dispatchEvent(mousemove); }
                        if (_x - x >= w) {
                            clearInterval(intervaltimer);
                            var mouseup = document.createEvent("MouseEvents");
                            mouseup.initMouseEvent("mouseup", true, true, window, 0, _x, _y, _x, _y, false, false, false, false, 0, null);
                            if (btn_slide != null) { btn_slide.dispatchEvent(mouseup); }
                             setTimeout(function() {
                                var nc_mask = document.querySelector("#nc_mask");
                            }, 2500);
                        } else {
                            dx += parseInt(Math.random() * (209 - 199) + 199) / 33;
                        }
                    }, 30);
                }
            }

将代码放入答题模块

**Comment by left0ver** [comment]
> 滑动验证代码如下，供参考
> 
> ```
>         function ncSlideVerify() {
>             if (nc_mask != null && getComputedStyle(nc_mask).display !== 'none') {
>                 var btn_slide = document.querySelector(".btn_slide");
>                 var mousedown = document.createEvent("MouseEvents");
>                 if (btn_slide != null) {
>                     var btn_slide_rect = btn_slide.getBoundingClientRect();
>                     var x = btn_slide_rect.left + btn_slide_rect.width * (parseInt(Math.random() * 5) / 10 + 0.2);
>                     var y = btn_slide_rect.top + btn_slide_rect.height / 2;
>                 }
>                 var nc_scale = document.querySelector(".nc_scale");
>                 if (nc_scale != null) { var w = nc_scale.getBoundingClientRect().width; }
>                 
>                 //点击滑块
>                 mousedown.initMouseEvent("mousedown", true, true, window, 0, x, y, x, y, false, false, false, false, 0, null);
>                 if (btn_slide != null) { btn_slide.dispatchEvent(mousedown); }
>                 
>                 var dx = 0;
>                 var dy = 0;
>                 //滑动滑块
>                 intervaltimer = setInterval(function() {
>                     var mousemove = document.createEvent("MouseEvents");
>                     var _x = x + dx;
>                     var _y = y + dy;
>                     mousemove.initMouseEvent("mousemove", true, true, window, 0, _x, _y, _x, _y, false, false, false, false, 0, null);
>                     if (btn_slide != null) { btn_slide.dispatchEvent(mousemove); }
>                     if (_x - x >= w) {
>                         clearInterval(intervaltimer);
>                         var mouseup = document.createEvent("MouseEvents");
>                         mouseup.initMouseEvent("mouseup", true, true, window, 0, _x, _y, _x, _y, false, false, false, false, 0, null);
>                         if (btn_slide != null) { btn_slide.dispatchEvent(mouseup); }
>                          setTimeout(function() {
>                             var nc_mask = document.querySelector("#nc_mask");
>                         }, 2500);
>                     } else {
>                         dx += parseInt(Math.random() * (209 - 199) + 199) / 33;
>                     }
>                 }, 30);
>             }
>         }
> ```
> 
> 将代码放入答题模块

亲测有效，需要改一些东西

**Comment by left0ver** [comment]
> 滑动验证代码如下，供参考
> 
> ```
>         function ncSlideVerify() {
>             if (nc_mask != null && getComputedStyle(nc_mask).display !== 'none') {
>                 var btn_slide = document.querySelector(".btn_slide");
>                 var mousedown = document.createEvent("MouseEvents");
>                 if (btn_slide != null) {
>                     var btn_slide_rect = btn_slide.getBoundingClientRect();
>                     var x = btn_slide_rect.left + btn_slide_rect.width * (parseInt(Math.random() * 5) / 10 + 0.2);
>                     var y = btn_slide_rect.top + btn_slide_rect.height / 2;
>                 }
>                 var nc_scale = document.querySelector(".nc_scale");
>                 if (nc_scale != null) { var w = nc_scale.getBoundingClientRect().width; }
>                 
>                 //点击滑块
>                 mousedown.initMouseEvent("mousedown", true, true, window, 0, x, y, x, y, false, false, false, false, 0, null);
>                 if (btn_slide != null) { btn_slide.dispatchEvent(mousedown); }
>                 
>                 var dx = 0;
>                 var dy = 0;
>                 //滑动滑块
>                 intervaltimer = setInterval(function() {
>                     var mousemove = document.createEvent("MouseEvents");
>                     var _x = x + dx;
>                     var _y = y + dy;
>                     mousemove.initMouseEvent("mousemove", true, true, window, 0, _x, _y, _x, _y, false, false, false, false, 0, null);
>                     if (btn_slide != null) { btn_slide.dispatchEvent(mousemove); }
>                     if (_x - x >= w) {
>                         clearInterval(intervaltimer);
>                         var mouseup = document.createEvent("MouseEvents");
>                         mouseup.initMouseEvent("mouseup", true, true, window, 0, _x, _y, _x, _y, false, false, false, false, 0, null);
>                         if (btn_slide != null) { btn_slide.dispatchEvent(mouseup); }
>                          setTimeout(function() {
>                             var nc_mask = document.querySelector("#nc_mask");
>                         }, 2500);
>                     } else {
>                         dx += parseInt(Math.random() * (209 - 199) + 199) / 33;
>                     }
>                 }, 30);
>             }
>         }
> ```
> 
> 将代码放入答题模块

大佬提一个pr吧

**Comment by McMug2020** [comment]
1、火狐兼容性问题
                    let firefoxVersion = (/Firefox\/([0-9]+)/.exec(navigator.userAgent) || [0, 0])[1];
                    if (firefoxVersion) { var window = document.defaultView; }
2、这个ncSlideVerify();滑动验证代码目前放到answer.js 答题提交时 延时运行就可以了，火狐需带入nc_mask参数

**Comment by vvwwind** [comment]
> 感觉老板提供的代码，已合并，新版本V3.0.5

大佬，3.05最新版，微软edge浏览器依然出现滑动验证，没有自动滑过

**Comment by McMug2020** [comment]
> > 感觉老板提供的代码，已合并，新版本V3.0.5
> 
> 大佬，3.05最新版，微软edge浏览器依然出现滑动验证，没有自动滑过

edge测试能通过，可能是鼠标在同时进行频繁操作导致的，可以监测并点击“刷新”的链接进行复位，或规定时间没滑过直接刷新（先行生成复位的链接）

**Comment by vvwwind** [comment]
哎呀，出错了，点击[刷新](javascript:__nc.reset())再来一次(error:kGr88p)

edge能滑动，提示这个错误

**Comment by vvwwind** [comment]
点刷新后，滑动正常

**Comment by McMug2020** [comment]
> 哎呀，出错了，点击刷新再来一次(error:kGr88p)
> 
> edge能滑动，提示这个错误

是每次都出现滑动错误吗？

**Comment by vvwwind** [comment]
> 

不是，刚才，直接没滑动。鼠标也一直不动

**Comment by McMug2020** [comment]
> > 
> 
> 不是，刚才，直接没滑动。鼠标也一直不动

我测试时没用原生的Edge，用的绿色版Chrome内核的Edge，你可以换个浏览器再试试看
