### ISSUE TITLE
请问如何解决谷歌浏览器应用商店无法响应的问题？

### ISSUE THREAD

**Issue by cherie9090222** [ttglad/learning#77]
代码小白一枚，不会用开发者模式，chrome也无法打开应用商店，Firefox又不更新了，每天陷入苦恼！！要不作者大大更新一下Firefox让我们这些小白也受益，感谢感谢！！

**Comment by left0ver** [comment]
你可以把master分支的代码下载下来，然后

**Comment by cherie9090222** [comment]
请问是每个代码都要加载吗？全部要下载下来？

**Comment by left0ver** [comment]
> 请问是每个代码都要加载吗？全部要下载下来？

<img width="979" alt="image" src="https://user-images.githubusercontent.com/89240290/207773792-8c8e0479-b827-4a80-98a6-1574f82c7a6a.png">
下载下来解压，之后Google插件点加载已解压的扩展程序，选中下载下来的代码中的release文件夹就行
