### ISSUE TITLE
请问如何下载到用于firefox的xpi文件？

### ISSUE THREAD

**Issue by zaonie** [ttglad/learning#82]
请问如何下载到用于firefox的xpi文件？
release里都是zip文件。。请问如何变成xpi？

**Comment by ttglad** [comment]
目前用的是V3版本，firefox不支持V3版本，建议使用谷歌浏览器

**Comment by zaonie** [comment]
> 目前用的是V3版本，firefox不支持V3版本，建议使用谷歌浏览器

收到。谢谢您的回复解答。
