### ISSUE TITLE
大佬，请教一下关于多用户

### ISSUE THREAD

**Issue by RioP777** [ttglad/learning#84]
每天还得给家里人做任务。
看见README中写“在Chrome中创建多个用户，使用不同的用户运行。”自己找了找，但是在chrome里并未找到该如何设置。只好来咨询大佬一下，感谢！

**Comment by RioP777** [comment]
Mac，Chrome111.0.5563.64 (正式版本) (x86_64) ，插件是v3.0,6

**Comment by xxrlzzz** [comment]
有个暴力点的方式: 开多个浏览器+无痕模式

**Comment by ttglad** [comment]
> 

谷歌浏览器有用户登录，可以开多个浏览器多个用户登录试试
<img width="288" alt="image" src="https://user-images.githubusercontent.com/7711709/226238633-e7409554-c8e6-4346-99a1-a3ca88a4411b.png">

**Comment by RioP777** [comment]
啊哈！谢谢！！
