### ISSUE TITLE
大佬，突然不能用了呀，多个浏览器都报错

### ISSUE THREAD

**Issue by wky030** [ttglad/learning#85]

**Comment by zhui22222** [comment]
说是查积分进度的接口改了，等作者更新

**Comment by wky030** [comment]
![image](https://user-images.githubusercontent.com/91868670/226091081-dbc9b4aa-73fa-4228-abb6-2ec639db9c95.png)

**Comment by wky030** [comment]
![image](https://user-images.githubusercontent.com/91868670/226091120-4c75ab6c-f38d-4965-b85a-c2ef4f85124a.png)

**Comment by wky030** [comment]
![image](https://user-images.githubusercontent.com/91868670/226091143-e9470884-e2f7-4649-aa75-f4dbe25eaec8.png)
