### ISSUE TITLE
不会自动学习了

### ISSUE THREAD

**Issue by cnnjgz** [ttglad/learning#88]
不知道什么原因，插件今天突然不会自动学习了，求解决方案

**Comment by gu5456** [comment]
同问

**Comment by huhurun** [comment]
同问

**Comment by huhurun** [comment]
手动点开做题，还是会自动做，其它的都不行了

**Comment by ggzxccf** [comment]
这是一个大佬修改过的一个仓库，着急的话可以先用这个https://github.com/left0ver/learning

**Comment by Fren-asdg** [comment]
我的也不能自动学习了，是什么原因呢？大家有解决的办法吗？

**Comment by ttglad** [comment]
今天发现又可以自动学习了，暂不做更新，观察先看看

**Comment by Northxw** [comment]
> 今天发现又可以自动学习了，暂不做更新，观察先看看

不行哇，我是 Windows10 Chrome 111.0.5563.65，大佬快看看

**Comment by ttglad** [comment]
> > 今天发现又可以自动学习了，暂不做更新，观察先看看
> 
> 不行哇，我是 Windows10 Chrome 111.0.5563.65，大佬快看看

我正在用啊，没问题啊，你有什么错误提示么

**Comment by Northxw** [comment]
> 

没有啥错误提示，正常点击学习然后扫码，它自己跳转到我的积分页面，然后就不动弹了，原本好像会直接跳转到答题页面。

然后，我刚才去试了下修改自动学习的配置，保存后重新开始学习，还是不动弹.....

**Comment by Northxw** [comment]
> > > 今天发现又可以自动学习了，暂不做更新，观察先看看
> > 
> > 
> > 不行哇，我是 Windows10 Chrome 111.0.5563.65，大佬快看看
> 
> 我正在用啊，没问题啊，你有什么错误提示么

我怀疑的两个点 ① 我电脑一周多时间没有关机了，不知道有没有影响  ② 我挂着梯子，之前我也是挂着梯子的，但是默认国内域名不走梯子，不清楚会不会影响

**Comment by ttglad** [comment]
> 我怀疑的两个点 ① 我电脑一周多时间没有关机了，不知道有没有影响 ② 我挂着梯子，之前我也是挂着梯子的，但是默认国内域名不走梯子，不清楚会不会影响

我这边确实可以，周末不可以的是因为查询积分接口有问题，今天看了是可以的，建议你关闭梯子重启浏览器试试。

**Comment by Northxw** [comment]
> > 我怀疑的两个点 ① 我电脑一周多时间没有关机了，不知道有没有影响 ② 我挂着梯子，之前我也是挂着梯子的，但是默认国内域名不走梯子，不清楚会不会影响
> 
> 我这边确实可以，周末不可以的是因为查询积分接口有问题，今天看了是可以的，建议你关闭梯子重启浏览器试试。

大佬，我提交了新 issue，你有空的话瞅瞅 https://github.com/ttglad/learning/issues/89

**Comment by ttglad** [comment]
用3.0.7版本
