### ISSUE TITLE
Chrome & QQ GG

### ISSUE THREAD

**Issue by Northxw** [ttglad/learning#89]
![image](https://user-images.githubusercontent.com/38708989/226265506-e82d0212-7da0-48a8-b6d0-e5ec4b00d560.png)

1. 早晨我用 Chrome 尝试重启浏览器、卸载重装插件、关闭梯子等操作，都没办法开始自动学习，也没有任何报错信息，但是我跟大佬对话之后，一度觉得是我自己的问题，因为他正常用的没问题。

2. 刚才安装了 QQ 浏览器，安装了插件，开启学习，扫码后显示 "**系统繁忙，请稍后再试**" 的报错信息，大佬看看吧，拯救孩子....

**Comment by left0ver** [comment]
还是无法自动学习吗？你使用最新的代码试一下

**Comment by Northxw** [comment]
最新现象，点击专项答题、每日答题等，进入答题界面后会自动答题，但是不会自动跳转，感觉是页面元素是不是有所变化了 @ttglad

**Comment by Northxw** [comment]
> 还是无法自动学习吗？你使用最新的代码试一下

我试试

**Comment by ttglad** [comment]
> 还是无法自动学习吗？你使用最新的代码试一下

周末不能使用的接口，我本地打开是没有问题的，难道是部分用户旧的接口打不开了么

**Comment by ttglad** [comment]
> > 还是无法自动学习吗？你使用最新的代码试一下
> 
> 谢谢大佬，我试了这个链接 https://github.com/left0ver/learning 的开发版本，一切正常

登录后，打开这个接口试试看呢 [积分](https://pc-proxy-api.xuexi.cn/api/score/days/listScoreProgress?sence=score&deviceType=2)

**Comment by Northxw** [comment]
> > > 还是无法自动学习吗？你使用最新的代码试一下
> > 
> > 
> > 谢谢大佬，我试了这个链接 https://github.com/left0ver/learning 的开发版本，一切正常
> 
> 登录后，打开这个接口试试看呢 [积分](https://pc-proxy-api.xuexi.cn/api/score/days/listScoreProgress?sence=score&deviceType=2)

这个没问题，积分正常
