### ISSUE TITLE
卡在“我的积分”页面了，有何办法解决

### ISSUE THREAD

**Issue by Kkkkkun** [ttglad/learning#90]
今天登陆进去就一直停在积分页面，对照测试了，是扫了我的号才出现的问题，换其他电脑依然，今天下午出现的这个问题

**Comment by Northxw** [comment]
下载 devlop 版本，昨天看到大佬已经合并新的提交了，如果不行，试试  https://github.com/left0ver/learning

**Comment by ttglad** [comment]
重新发了个3.0.7版本，再试试

**Comment by supertdd** [comment]
已试用3.0.7版本，卡我的积分问题解决，但今天出现了卡在阅读文章环节，即阅读完一篇文章后卡住，退出重新启动恢复。另，ka我的积分问题似乎不是普遍现象，有的同事使用正常

**Comment by supertdd** [comment]
经测试，卡我的积分顺利解读，但除了卡单个阅读文章外，也会卡阅读文章整体，即阅读文章完成后，不会自动跳转到阅读视频

**Comment by Kkkkkun** [comment]
好，谢谢，我试试

**Comment by CSZ112233** [comment]
QQ浏览器下载3.0.7版本还是卡积分界面没反应，火狐浏览器的积分界面不停的闪

**Comment by ttglad** [comment]
> QQ浏览器下载3.0.7版本还是卡积分界面没反应，火狐浏览器的积分界面不停的闪

使用chrome浏览器试试

**Comment by aerowang66** [comment]
![image](https://user-images.githubusercontent.com/128773883/227461176-2544b3a0-4b9f-4b39-b363-020e84d9d3b3.png)
通过拖动crx文件到chrome浏览来安装插件，然后提示不在应用商店中，右下角启动按钮是灰色，无法开启。请问这是有哪里不对 吗？
