### ISSUE TITLE
3.0.7版本打不开，是灰色的

### ISSUE THREAD

**Issue by sueyiya** [ttglad/learning#93]
点击不了，无法自动学习，360极速浏览器不行，希望可以兼容一下

**Comment by amor33** [comment]
同样的问题，希望可以解决下
![image](https://user-images.githubusercontent.com/20469760/226782069-10f1887a-39b2-4112-9da5-d455cc473a43.png)

**Comment by ttglad** [comment]
使用chrome浏览器啊，为啥要用360,360都是用的chrome内核

**Comment by amor33** [comment]
是360极速版，使用chromium内核是86版本，不可以兼容一下吗？

**Comment by amor33** [comment]
安装到chrome仍然不可使用，开关灰色不可打开
![image](https://user-images.githubusercontent.com/20469760/226843185-ff2c327d-258c-4b69-8223-087638188b8c.png)

**Comment by amor33** [comment]
![image](https://user-images.githubusercontent.com/20469760/226843317-97970e94-0400-4306-b071-b36ed71097df.png)

**Comment by ttglad** [comment]
> 安装到chrome仍然不可使用，开关灰色不可打开 ![image](https://user-images.githubusercontent.com/20469760/226843185-ff2c327d-258c-4b69-8223-087638188b8c.png)

两种方式，谷歌商店直接搜索下载官方商店的，第二种，开发者模式加载git上面的下载的代码

**Comment by ttglad** [comment]
> > 使用chrome浏览器啊，为啥要用360,360都是用的chrome内核
> 
> 国产电脑，银河麒麟的系统只有360

搜下为什么360不支持chrome浏览器插件吧

**Comment by amor33** [comment]
> > 使用chrome浏览器啊，为啥要用360,360都是用的chrome内核
> 
> 国产电脑，银河麒麟的系统只有360

试试这一版吧，是隔壁learningthepooh项目转向电报群内更新的，我试了360可以用
[學習小熊v1_7_1_桌面浏览器扩展_积分API接口修复.zip](https://github.com/ttglad/learning/files/11046121/v1_7_1_._.API.zip)
