### ISSUE TITLE
换了新版本忘记怎么使用了，有人可以来帮忙一下么

### ISSUE THREAD

**Issue by aerowang66** [ttglad/learning#95]
换了新版本忘记怎么使用了，有人可以来帮忙一下么。加我一下vx，6055758，谢谢！

之前使用1.0.4的，360浏览器，本周出现登录后就在我的积分页面不停自动刷新，无其他动作

来查阅换了3.0.7版本，360浏览器，插件安装过点击没有任何反应，安装到Chrome浏览器，提示未在应用商店列表中，无法使用。

**Comment by ttglad** [comment]
再试试3.0.7版本

**Comment by aerowang66** [comment]
> 再试3.0.7版
问题依旧，安装3.0.7插件后，360浏览器，点击红色图标，没有任何运行反应。

**Comment by aerowang66** [comment]
> 我试过了，edge确实可以使用，通过加载文件夹的方式。chrome也是需要通过加载文件夹，直接拖动crx我这里chrome会提示安全问题，由于不是来自应用商店。我最大的问题是360浏览器，此前版本的学习应该是1.0.7，此次更新后360浏览器提示如下错误。打开登录窗口存在错误，所以360点击开始学习完全没反应。不知道其他人情况如何。我先用chrome。谢谢老大

![微信图片_20230403091503](https://user-images.githubusercontent.com/128773883/229392154-8a8894be-58e7-4abe-9f47-28642e0a66db.png)
