### ISSUE TITLE
有大佬知道3.07新版本怎样安装吗

### ISSUE THREAD

**Issue by 220702199801229730** [ttglad/learning#97]
之前的一直在学习界面刷新，大家貌似都有这个问题，求保姆级教学

**Comment by aerowang66** [comment]
跟我是同款啊。。而且3.0不知道怎么安装了

**Comment by beyond510** [comment]
下载的ZIP包里有crx文件，百度一下怎么安装本地的crx插件就可以了

**Comment by aerowang66** [comment]
> 跟我是同款啊。。而且3.0不知道怎么安装了

管理扩展程序---加载已解压的扩展程序---选择release这个文件夹，即可安装成功

**Comment by aerowang66** [comment]
管理扩展程序---加载已解压的扩展程序---选择release这个文件夹，即可安装成功。
